MayBook/MayBook/Models/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MayBook.App_Data
{
    public class SearchController : Controller
    {
        //
        // GET: /Search/

        public ActionResult Index()
        {
            
            var context = new MayBookDataContext();
            var users = context.Users;
            return View(users);
        }

        [HttpPost]
        public ActionResult Index(string username)
        {
            if (username.Length == 0) return RedirectToAction("Index");
            var context = new MayBookDataContext();
            var users = context.Users.Where(u => u.Name == username);
            return View(users);
        }
    }
}

MayBook/MayBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/Scripts.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>MayBook</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Поиск", "Index", "Search")</li>
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Изменить профиль", "EditAccount", "Account")</li>
                    }
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

MayBook/MayBook/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Добро пожаловать, <strong>@ViewBag.Name!</strong>
    [ @Html.ActionLink("Выход", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Вход", "LogOn", "Account") ]
}